services:
  library:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password123
      MINIO_BUCKET: library-documents
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8002:8000"
    volumes:
      - ./src:/service/src
      - ./alembic.ini:/service/alembic.ini
    networks:
      - library-network
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    container_name: cram_library_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_library:/var/lib/postgresql/data
    networks:
      - library-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d library_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: library_minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio_data:/data
    networks:
      - library-network
    command: server /data --console-address ":9001"

  rabbitmq_1:
    image: rabbitmq:4-management
    container_name: rabbitmq_first
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data_1:/var/lib/rabbitmq
    restart: always

  rabbitmq_2:
    image: rabbitmq:4-management
    container_name: rabbitmq_second
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    volumes:
      - rabbitmq_data_2:/var/lib/rabbitmq
    restart: always


volumes:
  pgdata_library:
  rabbitmq_data_1:
  rabbitmq_data_2:

networks:
  library-network:
    driver: bridge
