"""added public field

Revision ID: bd3cd643ade6
Revises: c87bdc08e75e
Create Date: 2026-06-22 17:43:43.449346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3cd643ade6'
down_revision: Union[str, Sequence[str], None] = 'c87bdc08e75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'public')
    # ### end Alembic commands ###
