"""deleted minio raw key

Revision ID: c0dddc1d6f71
Revises: e95662718a98
Create Date: 2026-06-20 13:05:32.456911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dddc1d6f71'
down_revision: Union[str, Sequence[str], None] = 'e95662718a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('library_minio_raw_key_key'), 'library', type_='unique')
    op.drop_column('library', 'minio_raw_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('minio_raw_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('library_minio_raw_key_key'), 'library', ['minio_raw_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
