"""...

Revision ID: c87bdc08e75e
Revises: c0dddc1d6f71
Create Date: 2026-06-20 08:12:06.399213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87bdc08e75e'
down_revision: Union[str, Sequence[str], None] = 'c0dddc1d6f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'original_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'original_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
